Repository chain-ml/council, pull requests merged in 2023-07, with the labels that each got.

#1 Feature release pipeline
  .github/workflows/release.yaml
  .gitignore
  council_ai/__init__.py
  dev-requirements.txt
  pyproject.toml
  requirements.txt
  tests/unit/hello.py
Labels: release

#2 Publish to test PyPI and PyPI
  .github/workflows/release.yaml
  pyproject.toml
Labels: release

#9 Version 0.0.3
  pyproject.toml
Labels: release

#15 extract module controllers
  council/agents/agent.py
  council/controllers/__init__.py
  council/controllers/basic_controller.py
  council/controllers/controller_base.py
  council/controllers/llm_controller.py
  council/core/__init__.py
  docs/source/reference/controller.rst
  docs/source/reference/controller/basic_controller.rst
  docs/source/reference/controller/llm_controller.rst
  docs/source/reference/controllers.rst
  docs/source/reference/controllers/basic_controller.rst
  docs/source/reference/controllers/controller_base.rst
  docs/source/reference/controllers/llm_controller.rst
  docs/source/reference/core/controller_base.rst
  tests/integration/agent_tests/test_agent_test_suite.py
  tests/integration/controller/test_azure_llm_controller.py
  tests/integration/prompt/test_prompt.py
  tests/integration/skill/test_llm_sequence.py
  tests/integration/skill/test_llm_skill.py
  tests/unit/agents/test_agent.py
  tests/unit/controllers/__init__.py
  tests/unit/controllers/test_llm_controller.py
Labels: breaking change

#16 extract module evaluators
  README.md
  council/agents/agent.py
  council/core/__init__.py
  council/evaluators/__init__.py
  council/evaluators/basic_evaluator.py
  council/evaluators/evaluator_base.py
  council/evaluators/llm_evaluator.py
  docs/source/examples/my_first_agent.ipynb
  docs/source/reference/core/evaluator_base.rst
  docs/source/reference/evaluator.rst
  docs/source/reference/evaluator/basic_evaluator.rst
  docs/source/reference/evaluator/llm_evaluator.rst
  docs/source/reference/evaluators.rst
  docs/source/reference/evaluators/basic_evaluator.rst
  docs/source/reference/evaluators/evaluator_base.rst
  docs/source/reference/evaluators/llm_evaluator.rst
  tests/integration/agent_tests/test_agent_test_suite.py
  tests/integration/controllers/__init__.py
  tests/integration/controllers/test_azure_llm_controller.py
  tests/integration/evaluators/__init__.py
  tests/integration/evaluators/test_llm_evaluator.py
  tests/integration/prompt/test_prompt.py
  tests/integration/skill/test_llm_sequence.py
  tests/integration/skill/test_llm_skill.py
  tests/unit/agents/test_agent.py
  tests/unit/evaluators/__init__.py
  tests/unit/evaluators/test_llm_evaluator.py
Labels: breaking change

#17 Release 0.0.4
  pyproject.toml
Labels: release

#28 Release 0.0.5
  .github/workflows/release.yaml
  pyproject.toml
Labels: release, breaking change

#29 release 0.0.6
  pyproject.toml
Labels: release

#31 Provide consistent message iterator for all contexts
  README.md
  council/agents/agent_chain.py
  council/agents/agent_result.py
  council/contexts/__init__.py
  council/contexts/execution_context.py
  council/contexts/messages.py
  council/controllers/basic_controller.py
  council/controllers/controller_base.py
  council/controllers/llm_controller.py
  council/evaluators/basic_evaluator.py
  council/evaluators/evaluator_base.py
  council/evaluators/llm_evaluator.py
  council/llm/llm_message.py
  council/mocks/__init__.py
  council/prompt/prompt_builder.py
  council/runners/if_runner.py
  council/runners/runner_base.py
  council/scorers/llm_similarity_scorer.py
  council/scorers/scorer_base.py
  council/skills/google/google_news_skill.py
  council/skills/google/google_search_skill.py
  council/skills/llm_skill.py
  council/skills/skill_base.py
  docs/source/getting_started/first_example.ipynb
  docs/source/reference/contexts/agent_message.rst
  docs/source/reference/contexts/chat_message.rst
  docs/source/reference/contexts/chat_message_base.rst
  docs/source/reference/contexts/message_collection.rst
  docs/source/reference/contexts/scored_agent_message.rst
  docs/source/reference/contexts/scored_chat_message.rst
  docs/source/reference/contexts/skill_error_message.rst
  docs/source/reference/contexts/skill_message.rst
  docs/source/reference/contexts/skill_success_message.rst
  docs/source/reference/contexts/user_message.rst
  docs/source/reference/runners/parallel_for.rst
  docs/source/use_cases/multi_chain_agent.ipynb
  tests/integration/evaluators/test_llm_evaluator.py
  tests/integration/scorers/test_llm_similarity_score.py
  tests/integration/skill/test_google_skills.py
  tests/integration/skill/test_llm_sequence.py
  tests/unit/contexts/chat_message_base.py
  tests/unit/contexts/test_agent_result.py
  tests/unit/contexts/test_chat_history.py
  tests/unit/evaluators/test_llm_evaluator.py
  tests/unit/prompt/test_prompt.py
  tests/unit/runners/test_skill_runners.py
  tests/unit/scorers/test_llm_similarity_scorer.py
Labels: breaking change

#43 Release 0.0.7
  pyproject.toml
Labels: release, breaking change

#51 Version 0.0.8
  pyproject.toml
Labels: release
